create table if not exists public.users (
  id bigint generated by default as identity primary key,
  auth_uid uuid unique,
  name text not null,
  email text unique not null,
  password_hash text,
  role text not null default 'student' check (role in ('student','teacher')),
  created_at timestamptz not null default now()
);
create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  course_name text not null,
  teacher_id bigint not null references public.users(id),
  created_at timestamptz not null default now()
);
create table if not exists public.assignments (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  title text not null,
  description text not null,
  deadline timestamptz not null,
  max_marks integer not null,
  created_by bigint not null references public.users(id),
  allowed_file_types text not null default 'pdf,docx,zip',
  max_file_size_mb integer not null default 10,
  created_at timestamptz not null default now()
);
create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  assignment_id bigint not null references public.assignments(id) on delete cascade,
  student_id bigint not null references public.users(id),
  file_name text not null,
  file_url text,
  storage_path text not null,
  submitted_at timestamptz not null default now(),
  submission_status text not null,
  marks integer,
  feedback text,
  graded_at timestamptz,
  unique(assignment_id,student_id)
);
create index if not exists idx_assignments_course on public.assignments(course_id);
create index if not exists idx_submissions_assignment on public.submissions(assignment_id);
create index if not exists idx_submissions_student on public.submissions(student_id);
-- For a classroom demo, backend service-role access is used for data/storage operations.
-- If the client is allowed direct database access, add RLS policies before exposing tables.
